### ISSUE TITLE
Push tagged reqExec for Windows

### ISSUE THREAD

**Issue by rageshkrishna** [Shippable/shipit#41]
https://github.com/Shippable/heap/issues/1959

**Comment by rageshkrishna** [comment]
This will be verified after the next run of `prod_release`

**Comment by scriptnull** [comment]
`prod_release` is done and verified this by running 

```powershell
Invoke-WebRequest https://s3.amazonaws.com/shippable-artifacts/reqExec/v6.2.2/reqExec-v6
.2.2-x86_64-WindowsServer_2016.zip -OutFile reqexec-6.2.2.zip
```

On unzipping, we could see `dist/main/main.exe`
